version: '3.7'

services:
  ethereum-node:
    container_name: ethereum-main
    image: ethereum/client-go
    restart: always
    ports:
      - 8545:8545
      - 30303:30303
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /root/.ethereum:/root/.ethereum
    command:
      # - --syncmode=full