version: '3.1'

services:

  filebrowser:
    image: filebrowser/filebrowser
    restart: always
    ports:
      - 8090:80
    volumes:
      #- /data/filebrowser/filebrowser.db:/database.db
      - ./data:/srv
