#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#version: '3'

services:
    rsshub:
        image: diygod/rsshub
        restart: always
        ports:
            - '1100:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
            ACCESS_KEY: "xian"
        # volumes:
        #     - ./routes:/app/lib/routes
        depends_on:
            - redis
            - browserless

    browserless:
        # See issue 6680
        image: browserless/chrome:1.43-chrome-stable
        restart: always
        ports:
            - '3000:3000'
        ulimits:
            core:
                hard: 0
                soft: 0

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

volumes:
    redis-data:
		
version: '2'

networks:
  sftp:

services:
  sftp:
    container_name: sftp
    image: atmoz/sftp
    restart: always
    ports:
      - "2202:22"
    volumes:
      - ./data:/home/sftp
    command: sftp:123:1234
    networks:
      - sftp
