version: '3.7'

services:
  ethereum-rinkeby:
    container_name: ethereum-rinkeby
    image: ethereum/client-go
    restart: always
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/.ethereum:/root/.ethereum
    command:
      - --rinkeby
      - --ipcdisable # metaMask 钱包需要开启

      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      # - --http.api=admin debug web3 eth txpool personal clique miner net rpc

      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546

      --allow-insecure-unlock
      
    deploy: # 启动需要compatibility参数，ps:docker-compose --compatibility up -d
      resources:
          limits:
            memory: 2G    #内存限制
            # cpus: '0.5'   #cpu限制
