version: '2'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass 123456
    volumes:
      - /etc/localtime:/etc/localtime:ro
